MvcProjectCamp/Controllers/AuthorizationController.cs
using EntityLayer.Concrete;
using EntityLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;

namespace MvcProjectCamp.Controllers
{
    public class AuthorizationController : Controller
    {
        AdminManagerBL adminmanager = new AdminManagerBL(new EfAdminDAL());

        // GET: Authorization
        public ActionResult Index()
        {
            var adminvalues = adminmanager.GetList();
            return View(adminvalues);
        }
        [HttpGet]
        public ActionResult AddAdmin()
        {
            List<SelectListItem> valueAdminRole = new List<SelectListItem>();
            valueAdminRole.Add(new SelectListItem
            {
                Text = "A",
                Value = "A"

            });
            valueAdminRole.Add(new SelectListItem
            {
                Text = "B",
                Value = "B"

            });
            valueAdminRole.Add(new SelectListItem
            {
                Text = "C",
                Value = "C"

            });
            ViewBag.vlc = valueAdminRole;

            return View();
        }
        [HttpPost]
        public ActionResult AddAdmin(Admin p)
        {
            string encUsername = StaticHash.Encrypt(p.AdminUserName);
            string encPassword = StaticHash.Encrypt(p.AdminPassword);
            p.AdminUserName = encUsername;
            p.AdminPassword = encPassword;
            adminmanager.AdminAdd(p);
            return RedirectToAction("AddAdmin");
        }
        [HttpGet]
        public ActionResult EditAdmin(int id)
        {
            List<SelectListItem> valueAdminRole = new List<SelectListItem>();
            valueAdminRole.Add(new SelectListItem
            {
                Text = "A",
                Value = "A"

            });
            valueAdminRole.Add(new SelectListItem
            {
                Text = "B",
                Value = "B"

            });
            valueAdminRole.Add(new SelectListItem
            {
                Text = "C",
                Value = "C"

            });
            ViewBag.vlc = valueAdminRole;

            var adminValue = adminmanager.GetByID(id);
            return View(adminValue);
        }

        [HttpPost]
        public ActionResult EditAdmin(Admin p)
        {
            adminmanager.AdminUpdate(p);
            return RedirectToAction("Index");
        }
    }
}

MvcProjectCamp/Views/Authorization/AddAdmin.cshtml
@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "AddAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>Yeni Admin Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("AddAdmin", "Authorization", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Admin Kullanıcı Adı")
        @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })
        <br />
        @Html.Label("Şifreyi Giriniz")
        @Html.TextBoxFor(x => x.AdminPassword, new { @class = "form-control" })
        <br />
        @Html.Label("Rolü Seçiniz")
        @Html.DropDownListFor(x => x.AdminRole, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        <br />
        <button class="btn btn-info">Kaydet</button>
        <a href="/Authorization/Index" class="btn btn-warning"><i class="fas fa-backward"></i> Geri Dön</a>

    </div>
}

MvcProjectCamp/Views/Authorization/EditAdmin.cshtml
@model EntityLayer.Concrete.Admin

@{
    ViewBag.Title = "EditAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<br />
<h2>Admin Güncelleme Sayfası</h2>
@using (Html.BeginForm("EditAdmin", "Authorization", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.AdminID, new { @class = "form-control" })
        @Html.Label("Admin Kullanıcı Adı")
        @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })
        <br />
        @Html.Label("Şifre")
        @Html.TextBoxFor(x => x.AdminPassword, new { @class = "form-control" })
        <br />
        @Html.Label("Rol")
        @Html.DropDownListFor(x => x.AdminRole, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}

MvcProjectCamp/Views/Authorization/Index.cshtml
@using EntityLayer.Concrete
@model List<Admin>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<br />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kullanıcı Mail</th>
        <th>Yetki</th>
        <th>Status</th>
        <th>Pasif Yap</th>
        <th>Yetkisini Değiştir</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.AdminID</th>
            <td>@item.AdminUserName</td>
            <td>@item.AdminRole</td>
            <td>Aktif</td>
            <td><a href="/AdminCategory/DeleteCategory/@item.AdminID" class="btn btn-danger">Pasif Yap</a></td>
            <td><a href="/Authorization/EditAdmin/@item.AdminID" class="btn btn-warning">Yetkisini Değiştir</a></td>
            <td><a href="#" class="btn btn-primary">Başlıklar</a></td>
        </tr>
    }
</table>
<a href="/Authorization/AddAdmin/" class="btn btn-info">Yeni Admin Tanımla</a>